[package]
name = "cargo-license-folder"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.98", default-features = false }
itertools = { version = "0.14.0", default-features = false, features = ["use_std"] }
