[package]
name = "cargo-license-folder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", default-features = false, features = ["std", "derive"] }
anyhow = { version = "*", default-features = false }
itertools = { version = "*", default-features = false, features = ["use_std"] }