[package]
name = "cargo-license-folder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "*", default-features = false }
 
[workspace]
resolver = "2"
 
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
todo = "forbid"
dbg_macro = "forbid"
unwrap_used = "forbid"
print_stdout = "forbid"
print_stderr = "forbid"